### ISSUE TITLE
Incosistent integration test naming

### ISSUE THREAD

**Issue by gabrielKerekes** [vacuumlabs/ledgerjs-cardano-shelley#106]
Most of the integration tests are named `Should correctly sign tx with ...` but some of them are named `Transaction with ...` or `Mary era transaction with ...`. We should at some point align this.

Currently there's three levels of tests. E.g.
- `getExtendedPublicKey`:
    - `Should successfully get a single extended public key`:
        - `byron`
        - `shelley`
        - `shelley unusual`
        - `cold keys`
        
The first and third level are consistent overall. The inconsistencies lie only in the second level tests. My proposal would be to name the second level tests in accordance with the `Should correctly sign tx with ...` style. However, @janmazak proposed to shorten the test names in https://github.com/vacuumlabs/ledgerjs-cardano-shelley/pull/103#discussion_r633437489.

**Comment by janmazak** [comment]
Done in 43900029216bb733cd19da2fd6cb81f05063814d.
